import type { RefundRow } from '../models/refund.model';
import type { SaleStatus } from '@/modules/sale/models/sale.model';
import type { UpdateRefundCommand } from '../commands/update-refund.command';
import type { SearchRefundCommand } from '../commands/search-refund.command';

export type RefundSaleRef = { id: string; code: string; status: SaleStatus; price: string };
export type RefundClientRef = { id: string; name: string; code: string };
export type RefundUserRef = { id: string; name: string } | null;

/** A refund with the sale and client the listing shows. */
export type RefundListItem = RefundRow & { sale: RefundSaleRef | null; client: RefundClientRef | null };

export type RefundDetail = RefundListItem & { requestedByUser: RefundUserRef; resolvedByUser: RefundUserRef };

/** A sale that admits a refund (`active` or `cancelled`), for the create form. */
export type RefundableSale = { id: string; code: string; clientName: string | null; price: string; status: SaleStatus };

/** Fields persisted by `create`; the code (`REF000001`) is generated by the repository and the status is `pending`. */
export type NewRefundData = {
  id: string;
  companyId: string;
  saleId: string;
  clientId: string;
  amount: number;
  reason: string | null;
  requestedBy: string | null;
};

export interface RefundRepository {
  /** Single insert path for refunds (manual creation and the sale "Expulsar" flow). Must run inside a transaction. */
  create(data: NewRefundData): Promise<void>;
  findById(id: string, companyId: string): Promise<RefundDetail | null>;
  findOrFail(id: string, companyId: string): Promise<RefundDetail>;
  /** `SELECT … FOR UPDATE` on the refund row; must run inside the action's transaction. */
  lockById(id: string, companyId: string): Promise<RefundRow | null>;
  update(row: RefundRow, command: UpdateRefundCommand): Promise<void>;
  approve(row: RefundRow, resolvedBy: string | null): Promise<void>;
  reject(row: RefundRow, resolvedBy: string | null): Promise<void>;
  search(command: SearchRefundCommand): Promise<{ data: RefundListItem[]; total: number }>;
  listRefundableSales(companyId: string, limit: number): Promise<RefundableSale[]>;
}
