import type { BotProvider } from '../models/bot-channel.model';
import type { CreateBotChannelInput } from '../validation/create-bot-channel.schema';

export class CreateBotChannelCommand {
  constructor(
    readonly id: string,
    readonly companyId: string,
    readonly provider: BotProvider,
    readonly externalId: string,
    readonly displayName: string,
    readonly accessToken: string,
    readonly appSecret: string | null,
    readonly verifyToken: string | null,
    /** Generated by the service for Telegram; WhatsApp does not use it. */
    readonly webhookSecret: string | null,
    readonly wabaId: string | null,
    readonly graphApiVersion: string,
  ) {}

  static fromInput(
    input: CreateBotChannelInput,
    companyId: string,
    resolved: { externalId: string; displayName: string; webhookSecret: string | null },
  ): CreateBotChannelCommand {
    return new CreateBotChannelCommand(
      input.id,
      companyId,
      input.provider,
      resolved.externalId,
      resolved.displayName,
      input.accessToken,
      input.appSecret,
      input.verifyToken,
      resolved.webhookSecret,
      input.wabaId,
      input.graphApiVersion,
    );
  }
}
