import type { SaleCapacity, SaleRenewalRow, SaleRow } from '../models/sale.model';
import type { ClientStatus } from '@/modules/client/models/client.model';
import type { ProfileStatus } from '@/modules/account/models/account.model';
import type { LockedProfile } from '../domain/sale-rules';
import type { SearchSaleCommand } from '../commands/search-sale.command';

export type SaleClientRef = { id: string; name: string; code: string };
export type SalePlanRef = { id: string; name: string; code: string; durationDays: number; salePrice: string };
export type SaleServiceRef = { id: string; name: string; code: string; maxProfiles: number };
export type SaleAgentRef = { id: string; name: string };

/** A sale with the references the listing shows. `plan` carries the CURRENT plan values (not the snapshot). */
export type SaleListItem = SaleRow & {
  client: SaleClientRef | null;
  plan: SalePlanRef | null;
  service: SaleServiceRef | null;
  agent: SaleAgentRef | null;
};

export type SaleProfileItem = {
  id: string;
  profileId: string;
  number: number;
  profileStatus: ProfileStatus;
  account: { id: string; code: string; email: string };
  createdAt: Date;
};

export type SaleDetail = SaleListItem & { saleProfiles: SaleProfileItem[]; renewals: SaleRenewalRow[] };

export type SaleClientOption = { id: string; name: string; code: string; status: ClientStatus };
export type SaleServiceOption = { id: string; name: string; code: string };
export type SaleAgentOption = { id: string; name: string };
export type SalePlanOption = {
  id: string;
  name: string;
  code: string;
  serviceId: string;
  serviceName: string;
  maxProfiles: number;
  capacity: SaleCapacity;
  durationDays: number;
  salePrice: string;
};
export type SaleAvailableProfile = {
  id: string;
  number: number;
  accountId: string;
  accountCode: string;
  accountEmail: string;
  serviceId: string;
};

/** Fields persisted by `create`; the code (`SAL000001`) is generated by the repository. */
export type NewSaleData = {
  id: string;
  companyId: string;
  clientId: string;
  planId: string;
  agentId: string;
  serviceId: string;
  capacity: SaleCapacity;
  durationDays: number;
  price: number;
  startDate: string;
  endDate: string;
  notes: string | null;
};

export type SaleRenewalData = {
  id: string;
  renewedAt: string;
  previousEndDate: string;
  newEndDate: string;
  durationDays: number;
  price: number;
  renewedBy: string | null;
  notes: string | null;
};

export interface SaleRepository {
  create(data: NewSaleData): Promise<void>;
  findById(id: string, companyId: string): Promise<SaleRow | null>;
  findOrFail(id: string, companyId: string): Promise<SaleRow>;
  /** `SELECT … FOR UPDATE` on the sale row: serializes concurrent renew / reactivate / cancel. */
  findForUpdate(id: string, companyId: string): Promise<SaleRow | null>;
  findDetail(id: string, companyId: string): Promise<SaleDetail | null>;
  search(command: SearchSaleCommand): Promise<{ data: SaleListItem[]; total: number }>;

  findClient(clientId: string, companyId: string): Promise<SaleClientOption | null>;
  findPlan(planId: string, companyId: string): Promise<SalePlanOption | null>;
  findService(serviceId: string, companyId: string): Promise<SaleServiceRef | null>;

  /**
   * `SELECT … FOR UPDATE` on the profiles (with their account). Missing ids are simply absent.
   * `saleId` resolves `linkedToSale` / `heldByAnotherSale` for reactivation.
   */
  lockProfiles(profileIds: readonly string[], saleId?: string): Promise<LockedProfile[]>;
  profileIdsOf(saleId: string): Promise<string[]>;
  /** Inserts the `app_sale_profiles` rows and marks the profiles `occupied`. */
  assignProfiles(saleId: string, profileIds: readonly string[]): Promise<void>;
  /** Frees `releaseIds` (guarded), replaces the sale's pivot rows with `profileIds` and occupies them. */
  replaceProfiles(saleId: string, profileIds: readonly string[], releaseIds: readonly string[]): Promise<void>;

  /** Inserts the renewal, moves `endDate` and sets the sale `active`. */
  renew(sale: SaleRow, renewal: SaleRenewalData): Promise<void>;
  /** Inserts the renewal and resets the sale cycle: endDate, price, durationDays, active, cancellation cleared. */
  reactivate(sale: SaleRow, renewal: SaleRenewalData): Promise<void>;
  /**
   * Marks the sale `cancelled` (now + reason) and frees its occupied profiles that no newer
   * non-cancelled sale holds. Reused by the refund approval flow.
   */
  cancel(sale: SaleRow, reason: string): Promise<void>;

  /** Expiration job (every company). */
  findDueActiveSaleIds(today: string): Promise<string[]>;
  markExpired(saleId: string, today: string): Promise<boolean>;
  findExpiredSaleIdsEndingBefore(cutoff: string): Promise<string[]>;
  /** Frees the sale's occupied profiles (guarded like `cancel`). Returns how many were freed. */
  releaseProfiles(saleId: string): Promise<number>;

  searchActiveClients(companyId: string, term: string, limit: number): Promise<SaleClientOption[]>;
  listClients(companyId: string): Promise<SaleClientOption[]>;
  listServices(companyId: string): Promise<SaleServiceOption[]>;
  listAgents(companyId: string): Promise<SaleAgentOption[]>;
  listActivePlans(companyId: string): Promise<SalePlanOption[]>;
  listAvailableProfiles(companyId: string, serviceId?: string): Promise<SaleAvailableProfile[]>;
}
