import type { ServiceRow } from '../models/service.model';
import type { ServiceRepository } from '../repositories/service.repository';
import type { CreateServiceCommand } from '../commands/create-service.command';
import { ServiceNameAlreadyExistsException } from '../exceptions/service-name-already-exists.exception';

/** Crear: the name is unique per company (case-insensitive); the code (`SER000001`) is generated by the repository. */
export class ServiceCreateService {
  constructor(private readonly repository: ServiceRepository) {}

  async execute(command: CreateServiceCommand): Promise<ServiceRow> {
    if (await this.repository.existsByName(command.name, command.companyId)) {
      throw new ServiceNameAlreadyExistsException();
    }
    await this.repository.create(command);
    return this.repository.findOrFail(command.id, command.companyId);
  }
}
