import type { z } from 'zod';
import { requiredUuid } from '@/modules/shared/validation/fields';
import { keepCustomPermissions, roleFieldsSchema } from './update-role.schema';

/** Crear: the id is generated by the client (UUID v7). */
export const createRoleSchema = roleFieldsSchema.extend({ id: requiredUuid() }).transform(keepCustomPermissions);

export type CreateRoleInput = z.infer<typeof createRoleSchema>;
