import type { z } from 'zod';
import { requiredUuid } from '@/modules/shared/validation/fields';
import { updateCompanySchema } from './update-company.schema';

/** Crear: the id is generated by the client (UUID v7). */
export const createCompanySchema = updateCompanySchema.extend({ id: requiredUuid() });

export type CreateCompanyInput = z.infer<typeof createCompanySchema>;
