import type { z } from 'zod';
import { requiredUuid } from '@/modules/shared/validation/fields';
import { updatePlanSchema } from './update-plan.schema';

/** Crear: the id is generated by the client (UUID v7). New plans are always active. */
export const createPlanSchema = updatePlanSchema.extend({ id: requiredUuid() });

export type CreatePlanInput = z.infer<typeof createPlanSchema>;
