import { z } from 'zod';
import { optionalText, requiredUuid } from '@/modules/shared/validation/fields';
import { ACCOUNT_STATUSES } from '../models/account.model';
import {
  jsonArray,
  profileNumber,
  profileText,
  requiredAccountEmail,
  requiredAmount,
  requiredIsoDate,
  requiredPassword,
} from './account-fields';

const createProfileLine = z.object({
  number: profileNumber,
  pin: profileText('El PIN', 10).transform((v) => v ?? null),
});

/**
 * Crear. The id is generated by the client (UUID v7). Rules that need the database
 * (service of the company, email unique per service, profile number ≤ service.maxProfiles) live in the service.
 */
export const createAccountSchema = z
  .object({
    id: requiredUuid(),
    serviceId: requiredUuid('Selecciona un servicio válido.'),
    email: requiredAccountEmail,
    password: requiredPassword,
    cost: requiredAmount('El costo'),
    purchaseDate: requiredIsoDate('La fecha de compra'),
    nextRenewal: requiredIsoDate('La próxima renovación'),
    status: z.preprocess(
      (v) => (v === '' || v === null ? undefined : v),
      z.enum(ACCOUNT_STATUSES, { message: 'El estado no es válido.' }).default('active'),
    ),
    notes: optionalText('La nota'),
    profiles: jsonArray(createProfileLine).superRefine((lines, ctx) => {
      const seen = new Set<number>();
      lines.forEach((line, index) => {
        if (seen.has(line.number)) {
          ctx.addIssue({
            code: 'custom',
            path: [index, 'number'],
            message: `El número de perfil ${line.number} está duplicado.`,
          });
        }
        seen.add(line.number);
      });
    }),
  })
  .superRefine((data, ctx) => {
    if (data.nextRenewal < data.purchaseDate) {
      ctx.addIssue({
        code: 'custom',
        path: ['nextRenewal'],
        message: 'La próxima renovación no puede ser anterior a la fecha de compra.',
      });
    }
  });

export type CreateAccountInput = z.infer<typeof createAccountSchema>;
