import type { z } from 'zod';
import { requiredUuid } from '@/modules/shared/validation/fields';
import { updateClientSchema } from './update-client.schema';

/** Crear: the id is generated by the client (UUID v7). Email uniqueness is a business rule (service). */
export const createClientSchema = updateClientSchema.extend({ id: requiredUuid() });

export type CreateClientInput = z.infer<typeof createClientSchema>;
