import type { RenewAccountInput } from '../validation/renew-account.schema';

export class RenewAccountCommand {
  constructor(
    /** Id of the new `account_renewals` row (generated by the client). */
    readonly id: string,
    readonly companyId: string,
    readonly accountId: string,
    readonly createdBy: string | null,
    readonly amount: number,
    readonly nextRenewal: string,
    readonly notes: string | null,
  ) {}

  static fromInput(
    input: RenewAccountInput,
    companyId: string,
    accountId: string,
    createdBy: string | null,
  ): RenewAccountCommand {
    return new RenewAccountCommand(
      input.id,
      companyId,
      accountId,
      createdBy,
      input.amount,
      input.nextRenewal,
      input.notes,
    );
  }
}
