import type { ClientRow } from '../models/client.model';
import type { ClientRepository } from '../repositories/client.repository';
import type { CreateClientCommand } from '../commands/create-client.command';
import { ClientEmailAlreadyExistsException } from '../exceptions/client-email-already-exists.exception';

/** Crear: the email is unique per company; the code (`CLI000001`) is generated by the repository. */
export class ClientCreateService {
  constructor(private readonly repository: ClientRepository) {}

  async execute(command: CreateClientCommand): Promise<ClientRow> {
    if (command.email && (await this.repository.existsByEmail(command.email, command.companyId))) {
      throw new ClientEmailAlreadyExistsException();
    }
    await this.repository.create(command);
    return this.repository.findOrFail(command.id, command.companyId);
  }
}
