import type { z } from 'zod';
import { requiredUuid } from '@/modules/shared/validation/fields';
import { updateServiceSchema } from './update-service.schema';

/** Crear: the id is generated by the client (UUID v7). New services are always active. */
export const createServiceSchema = updateServiceSchema.extend({ id: requiredUuid() });

export type CreateServiceInput = z.infer<typeof createServiceSchema>;
