import type { PlanRecord, PlanRepository } from '../repositories/plan.repository';
import type { CreatePlanCommand } from '../commands/create-plan.command';
import { PlanInvalidServiceException } from '../exceptions/plan-invalid-service.exception';

/** Crear: the service must belong to the same company; the code (`PLA000001`) is generated by the repository. */
export class PlanCreateService {
  constructor(private readonly repository: PlanRepository) {}

  async execute(command: CreatePlanCommand): Promise<PlanRecord> {
    if (!(await this.repository.serviceExists(command.serviceId, command.companyId))) {
      throw new PlanInvalidServiceException();
    }
    await this.repository.create(command);
    return this.repository.findOrFail(command.id, command.companyId);
  }
}
